export const COM_LOADING_STATUS = 'COM_LOADING_STATUS'
export const COM_CONF = 'COM_CONF'
export const CHANGE_LEFTNAV_STATUS = 'CHANGE_LEFTNAV_STATUS'

export const HOME_GET_BANNER_LIST = 'HOME_GET_BANNER_LIST'
export const HOME_GET_NOWPLAYING_LIST = 'HOME_GET_NOWPLAYING_LIST'
export const HOME_GET_COMINGSOON_LIST = 'HOME_GET_COMINGSOON_LIST'

export const DETAIL_GET_INFO = 'DETAIL_GET_INFO'

export const CINEMA_GET_LIST = 'CINEMA_GET_LIST'

export const FILM_GET_NOWPLAYING = 'FILM_GET_NOWPLAYING'
export const FILM_NOWPLAYING_NUM = 'FILM_NOWPLAYING_NUM'
export const FILM_GET_COMINGSOON = 'FILM_GET_COMINGSOON'
export const FILM_COMINGSOON_NUM = 'FILM_COMINGSOON_NUM'
