// 订阅公众号号
export const SUBSCRIBE_MP = 'SUBSCRIBE_MP'

// 取消订阅
export const UNSUBSCRIBE_MP = 'UNSUBSCRIBE_MP'

export const ADD_SEARCHRESULT_LIST = 'ADD_SEARCHRESULT_LIST'
export const UNSUBSCRIBE_SEARCHRESULT = 'UNSUBSCRIBE_SEARCHRESULT'
export const CLEAR_SEARCHRESULT = 'CLEAR_SEARCHRESULT'

export const INIT_FROM_LS = 'INIT_FROM_LS'
